### ISSUE TITLE
unable to import the  "com.xw.repo.BubbleSeekBar library"

### ISSUE THREAD

**Issue by Sagar19RaoRane** [sinansonmez/WaterTracker#2]
i added the dependency in gradle file but unable to import this particular library

**Comment by sinansonmez** [comment]
Please share your gradle file and exact error message. So we can see if the problem is due to the project or the library

**Comment by Sagar19RaoRane** [comment]
'''
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk 30

    defaultConfig {
        applicationId "com.example.watertracker"
        minSdk 21
        targetSdk 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }



    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }


    dataBinding {
        enabled true
    }
}


dependencies {

    def room_version = "2.2.3"


    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'androidx.core:core-ktx:1.6.0'
    implementation "androidx.room:room-runtime:$room_version"

   implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.0'
    implementation 'androidx.vectordrawable:vectordrawable:1.1.0'
    implementation 'androidx.navigation:navigation-fragment:2.3.5'
    implementation 'androidx.navigation:navigation-ui:2.3.5'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.3.5'
    implementation 'androidx.navigation:navigation-ui-ktx:2.3.5'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.4.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    //material
    implementation 'com.google.android.material:material:1.5.0-alpha02'

    //seekbar https://github.com/woxingxiao/BubbleSeekBar
    implementation 'com.xw.repo:bubbleseekbar:3.20'

    // radiobutton https://github.com/ceryle/RadioRealButton
    implementation 'com.github.patgdut:RadioRealButton:v2.1.2'

   implementation 'com.jakewharton.timber:timber:5.0.1'
}
'''

**Comment by Sagar19RaoRane** [comment]
after sync now . following is the Gradle error

```
Failed to resolve: com.xw.repo:bubbleseekbar:3.20
Show in Project Structure dialog
Affected Modules: app
```

**Comment by sinansonmez** [comment]
Did you try to do File -> Invalidate Cache and Code -> Clean & Rebuild

**Comment by sinansonmez** [comment]
I close this issue due to inactivity
